/**
 * Build nodes/editor/icons.svg — the React Editor's file-tree icon sprite.
 *
 * The tree wears the same Lucide icons as the node badges on the canvas, so a
 * portal reads as a portal in both places. Path data comes from
 * tools/lucide-icons.mjs, shared with tools/build-icon.mjs.
 *
 * Run: node tools/build-sprite.mjs
 */
import { writeFileSync } from 'node:fs';
import { ICONS, VIEW_BOX, STROKE_ATTRS } from './lucide-icons.mjs';

// Only what the tree draws. The header and status-bar buttons stay on the Font
// Awesome that Node-RED already loads — they are its chrome, not ours.
const IN_SPRITE = [
  'atom',
  'component',
  'wrench',
  'codeXml',
  'folder',
  'folderOpen',
  'workflow',
  'ban',
  'chevronRight',
  'chevronDown',
];

/**
 * kebab-case id, so the markup reads `#fc-icon-folder-open` rather than the
 * camelCase key used on the JS side.
 * @param {string} key
 * @returns {string}
 */
const idOf = (key) => 'fc-icon-' + ICONS[key].lucide;

const symbols = IN_SPRITE.map((key) => {
  const icon = ICONS[key];
  if (!icon) throw new Error(`unknown icon: ${key}`);
  return `  <symbol id="${idOf(key)}" viewBox="${VIEW_BOX}" ${STROKE_ATTRS}>
${icon.body
  .split('\n')
  .map((l) => '    ' + l)
  .join('\n')}
  </symbol>`;
}).join('\n');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="display:none" aria-hidden="true">
  <!-- Generated by tools/build-sprite.mjs — do not edit.
       Icons from Lucide (https://lucide.dev), ISC — see THIRD-PARTY-NOTICES.md.
       Stroke is currentColor and stroke-width is a presentation attribute, so
       the page can recolour and thicken each use from CSS. -->
${symbols}
</svg>
`;

writeFileSync(new URL('../nodes/editor/icons.svg', import.meta.url), svg);
console.log('icons.svg:', IN_SPRITE.length, 'symbols,', svg.length, 'bytes');
